### ISSUE TITLE
WebSocketController doesn't inject WebSocketEvent

### ISSUE THREAD

**Issue by thosakwe** [angel-dart/websocket#26]

**Comment by sanketwarule** [comment]
I am new to the dart as well as angel websocket, I want to make a websocket demo for handling events, I followed your "from scrath tutorial " but didnt succeed.
Please help me to find out the issue in following code. The websocket event is not triggered.

Server file..
[server.txt](https://github.com/angel-dart/websocket/files/2240548/server.txt)

lib/angel_hello file..
[angel_hello.txt](https://github.com/angel-dart/websocket/files/2240553/angel_hello.txt)

test/websocket_test file..
[websocket_test.txt](https://github.com/angel-dart/websocket/files/2240559/websocket_test.txt)

pubspec.yaml file...
[pubspec.txt](https://github.com/angel-dart/websocket/files/2240561/pubspec.txt)

Please give me a simple demo working code for angel websocket if possible
