### ISSUE TITLE
Is it possible to use it with flutter and signalr ?

### ISSUE THREAD

**Issue by diegomgarcia** [angel-dart/websocket#50]
Hi I need to comunicate with a signalr app using websocket and flutter, do you know if its possible using your lib ?

Or have any tips on how to accomplish that ?

**Comment by thosakwe** [comment]
I know just about nothing about SignalR, so it's hard for me to answer that.

Angel websocket has two components:
* The server-side, specifically designed to handle WebSockets within an Angel server
* The client-side, which connects a WebSocket to an Angel backend, and parses the response into a format supported by the `angel_client` library.

If you're using Flutter and need to connect a WebSocket to an arbitrary server, then use the [`WebSocket` class from `dart:io`](https://api.dartlang.org/stable/1.24.3/dart-io/WebSocket-class.html).
